# Generated by Django 5.2.7 on 2025-12-08 08:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.TextField(max_length=100, null=True)),
                ('tipoEvento', models.TextField(max_length=200)),
                ('dataIni', models.DateField()),
                ('dataFin', models.DateField()),
                ('horasIni', models.TimeField(blank=True, null=True)),
                ('horasFin', models.TimeField(blank=True, null=True)),
                ('horasDura', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('local', models.TextField(max_length=200)),
                ('quantPart', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('vagas', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('certificado', models.BooleanField(default=False)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banners/')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.TextField(max_length=150)),
                ('telefone', models.CharField(max_length=15, null=True)),
                ('instEnsino', models.TextField(max_length=100, null=True)),
                ('senha', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('token_acesso', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(choices=[('estudante', 'Estudante'), ('professor', 'Professor'), ('organizador', 'Organizador')], default='Estudante', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('horaAcao', models.DateTimeField(auto_now_add=True)),
                ('dataAcao', models.DateField(auto_now_add=True, null=True)),
                ('acao', models.CharField(max_length=300)),
                ('id_evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.evento')),
                ('usuario_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Inscrito',
            fields=[
                ('id_inscricao', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('evento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.evento')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='organizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_criados', to='login.usuario'),
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id_carrinho', models.AutoField(primary_key=True, serialize=False)),
                ('dataEmissao', models.DateField(default=django.utils.timezone.now)),
                ('horas', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('evento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='login.evento')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.usuario')),
            ],
        ),
    ]
