# Generated by Django 5.2.5 on 2025-10-06 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.TextField(max_length=150)),
                ('senha', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=254, unique=True)),
            ],
        ),
    ]
