# Generated by Django 5.2.7 on 2025-12-07 02:13

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.TextField(max_length=100, null=True)),
                ('tipoEvento', models.TextField(max_length=200)),
                ('dataIni', models.DateField()),
                ('dataFin', models.DateField()),
                ('horasIni', models.TimeField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('horasFin', models.TimeField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('horasDura', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('local', models.TextField(max_length=200)),
                ('quantPart', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('organizador', models.TextField(max_length=200)),
                ('vagas', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('certificado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.TextField(max_length=150)),
                ('telefone', models.CharField(max_length=15, null=True)),
                ('instEnsino', models.TextField(max_length=100, null=True)),
                ('senha', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tipo', models.CharField(choices=[('estudante', 'Estudante'), ('professor', 'Professor'), ('organizador', 'Organizador')], default='Estudante', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Inscrito',
            fields=[
                ('id_inscricao', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('evento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.evento')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id_carrinho', models.AutoField(primary_key=True, serialize=False)),
                ('dataEmissao', models.DateField(default=django.utils.timezone.now)),
                ('horas', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('evento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='login.evento')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.usuario')),
            ],
        ),
    ]
