# Generated by Django 5.2.5 on 2025-10-07 21:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.TextField(max_length=100, null=True)),
                ('tipoEvento', models.TextField(max_length=200)),
                ('dataIni', models.DateField()),
                ('dataFin', models.DateField()),
                ('horarioIni', models.TimeField()),
                ('horarioFin', models.TimeField()),
                ('horasDura', models.TimeField(blank=True, null=True)),
                ('local', models.TextField(max_length=200)),
                ('quantPart', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('organizador', models.TextField(max_length=200)),
                ('vagas', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('certificado', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='instEnsino',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('estudante', 'Estudante'), ('professor', 'Professor')], default='Estudante', max_length=50),
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id_carrinho', models.AutoField(primary_key=True, serialize=False)),
                ('dataEmissao', models.DateField(default=django.utils.timezone.now)),
                ('horas', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.usuario')),
                ('evento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='login.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Inscrito',
            fields=[
                ('id_inscricao', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('evento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.evento')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.usuario')),
            ],
        ),
    ]
