# Generated by Django 5.2.7 on 2025-12-07 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='horasFin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='horasIni',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
