# Generated by Django 5.2.5 on 2025-10-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_evento_usuario_instensino_usuario_telefone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
