# Generated by Django 5.2.5 on 2025-12-07 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_log_dataacao_alter_log_id_evento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='id_evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.evento'),
        ),
        migrations.AlterField(
            model_name='log',
            name='usuario_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.usuario'),
        ),
    ]
