# Generated by Django 5.2.7 on 2025-12-07 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_evento_horasfin_alter_evento_horasini'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='horasDura',
            field=models.DurationField(),
        ),
    ]
