# Generated by Django 5.2.5 on 2025-10-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('estudante', 'Estudante'), ('professor', 'Professor'), ('organizador', 'Organizador')], default='Estudante', max_length=50),
        ),
    ]
