# Generated by Django 5.2.7 on 2025-10-13 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_usuario_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='horarioFin',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='horarioIni',
        ),
    ]
