# Generated by Django 5.2.5 on 2025-12-06 22:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_evento_horasfin_evento_horasini_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='horasFin',
            field=models.TimeField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='evento',
            name='horasIni',
            field=models.TimeField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='evento',
            name='quantPart',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
