# Generated by Django 5.2.5 on 2025-12-06 22:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_alter_evento_horasfin_alter_evento_horasini_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='quantPart',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
