# Generated by Django 5.2.5 on 2025-12-06 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_alter_evento_horasfin_alter_evento_horasini'),
        ('login', '0009_alter_evento_quantpart'),
    ]

    operations = [
    ]
