# Generated by Django 5.2.5 on 2025-12-07 01:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_merge_20251206_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='assinatura',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='horasDura',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
